model:
  model_name: "Qwen/Qwen3-0.6B"
  dtype: "bfloat16"

model_parameters:
  temperature: 0.0

extras:
  enable_thinking: false
  use_chat_template: true
  system_prompt: "Vous êtes un assistant utile."
  num_runs: 1
  output_dir: "results/"
  save_details: true
  push_to_hub: false

tasks:
  # - "community|ifeval-fr|0|1"
  # - "community|gpqa-diamond-fr|0|1"
  # - "community|bbh-fr|0|1"
  # - "community|hellaswag-fr|0|1"
  - "community|boolq-fr|0|1"
  # - "community|mmlu_fr|0|1"
  # - "community|musr-fr|0|1"
  # - "community|math-hard-fr|0|1" # 4 shots under the hood
